// technologies.js

const technologies = [
  { name: "Node.js", url: "https://nodejs.org/docs/latest/api/" },
  { name: "React", url: "https://react.dev/reference/react" },
  { name: "Python", url: "https://docs.python.org/3/" },
  { name: "Docker", url: "https://docs.docker.com/" },
  { name: "Kubernetes", url: "https://kubernetes.io/docs/home/" },
  { name: "Angular", url: "https://angular.io/docs" },
  { name: "TypeScript", url: "https://www.typescriptlang.org/docs/" },
  { name: "Java", url: "https://docs.oracle.com/en/java/" },
  { name: "Go", url: "https://golang.org/doc/" },
  { name: "Django", url: "https://docs.djangoproject.com/en/stable/" },
  { name: "Flask", url: "https://flask.palletsprojects.com/en/latest/" },
  { name: "PostgreSQL", url: "https://www.postgresql.org/docs/" },
  { name: "MySQL", url: "https://dev.mysql.com/doc/" },
  { name: "Redis", url: "https://redis.io/documentation" },
  { name: "MongoDB", url: "https://docs.mongodb.com/" },
  { name: "Vue.js", url: "https://vuejs.org/v2/guide/" },
  { name: "Express.js", url: "https://expressjs.com/en/4x/api.html" },
  { name: "Laravel", url: "https://laravel.com/docs/" },
  { name: "Ruby on Rails", url: "https://guides.rubyonrails.org/" },
  { name: "Swift", url: "https://swift.org/documentation/" },
  { name: "C", url: "https://en.cppreference.com/w/c" },
  { name: "C++", url: "https://en.cppreference.com/w/cpp" },
  { name: "C#", url: "https://docs.microsoft.com/en-us/dotnet/csharp/" },
  { name: "PHP", url: "https://www.php.net/manual/en/" },
  { name: "Ruby", url: "https://www.ruby-lang.org/en/documentation/" },
  { name: "Rust", url: "https://doc.rust-lang.org/book/" },
  { name: "Scala", url: "https://docs.scala-lang.org/" },
  { name: "Haskell", url: "https://www.haskell.org/documentation/" },
  { name: "SQL", url: "https://www.sqltutorial.org/" },
  { name: "NoSQL", url: "https://www.mongodb.com/nosql-explained" },
  { name: "GraphQL", url: "https://graphql.org/learn/" },
  {
    name: "Elasticsearch",
    url: "https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html",
  },
  { name: "TensorFlow", url: "https://www.tensorflow.org/api_docs" },
  { name: "PyTorch", url: "https://pytorch.org/docs/stable/index.html" },
  { name: "Android", url: "https://developer.android.com/docs" },
  { name: "iOS", url: "https://developer.apple.com/documentation" },
  { name: "SwiftUI", url: "https://developer.apple.com/documentation/swiftui" },
  { name: "OpenCV", url: "https://docs.opencv.org/master/" },
  { name: "MATLAB", url: "https://www.mathworks.com/help/matlab/" },
  { name: "Jupyter", url: "https://jupyter.org/documentation" },
  { name: "Kotlin", url: "https://kotlinlang.org/docs/home.html" },
  { name: "Tailwind CSS", url: "https://tailwindcss.com/docs" },
  { name: "Sass", url: "https://sass-lang.com/documentation" },
  { name: "WebAssembly", url: "https://webassembly.org/docs/" },
  { name: "REST", url: "https://restfulapi.net/" },
  { name: "DevOps", url: "https://www.atlassian.com/devops" },
  { name: "Agile", url: "https://www.agilealliance.org/agile101/" },
  {
    name: "Machine Learning",
    url: "https://www.ibm.com/cloud/learn/machine-learning",
  },
  {
    name: "Artificial Intelligence",
    url: "https://www.ibm.com/cloud/learn/what-is-artificial-intelligence",
  },
  {
    name: "Cybersecurity",
    url: "https://www.cyber.gov.au/acsc/view-all-content/publications/cyber-security-guide",
  },
  { name: "Data Science", url: "https://www.datascience.org/resources/" },
  { name: "Blockchain", url: "https://www.ibm.com/topics/what-is-blockchain" },
  {
    name: "Virtual Reality",
    url: "https://www.vive.com/us/learn/virtual-reality/",
  },
  {
    name: "Augmented Reality",
    url: "https://www.microsoft.com/en-us/hololens",
  },
  {
    name: "Internet of Things (IoT)",
    url: "https://www.ibm.com/internet-of-things",
  },
  { name: "Quantum Computing", url: "https://quantum-computing.ibm.com/docs" },

  { name: "Symfony", url: "https://symfony.com/doc/current/index.html" },
  { name: "Spring Boot", url: "https://spring.io/projects/spring-boot" },
  { name: "Hibernate", url: "https://hibernate.org/orm/documentation/5.4/" },
  {
    name: "Flask RESTful",
    url: "https://flask-restful.readthedocs.io/en/latest/",
  },
  { name: "Pandas", url: "https://pandas.pydata.org/docs/" },
  { name: "NumPy", url: "https://numpy.org/doc/stable/" },
  {
    name: "Scikit-learn",
    url: "https://scikit-learn.org/stable/user_guide.html",
  },
  { name: "Apache Spark", url: "https://spark.apache.org/docs/latest/" },
  { name: "Apache Kafka", url: "https://kafka.apache.org/documentation/" },
  { name: "RabbitMQ", url: "https://www.rabbitmq.com/documentation.html" },
  { name: "Terraform", url: "https://www.terraform.io/docs/index.html" },
  {
    name: "Ansible",
    url: "https://docs.ansible.com/ansible/latest/index.html",
  },
  { name: "Jenkins", url: "https://www.jenkins.io/doc/" },
  { name: "CircleCI", url: "https://circleci.com/docs/" },
  { name: "Git", url: "https://git-scm.com/doc" },
  { name: "GitHub", url: "https://docs.github.com/en" },
  { name: "GitLab", url: "https://docs.gitlab.com/ee/user/README.html" },
  {
    name: "Bitbucket",
    url: "https://support.atlassian.com/bitbucket-cloud/docs/",
  },
  { name: "Visual Studio Code", url: "https://code.visualstudio.com/docs" },
  { name: "Eclipse", url: "https://www.eclipse.org/documentation/" },
  {
    name: "IntelliJ IDEA",
    url: "https://www.jetbrains.com/idea/documentation/",
  },
  { name: "Xcode", url: "https://developer.apple.com/documentation/xcode" },
  { name: "Unity", url: "https://docs.unity3d.com/Manual/index.html" },
  {
    name: "Unreal Engine",
    url: "https://docs.unrealengine.com/en-US/index.html",
  },
  { name: "Figma", url: "https://www.figma.com/resources/learn-design/" },
  { name: "Adobe XD", url: "https://www.adobe.com/products/xd/resources.html" },
  { name: "Blender", url: "https://docs.blender.org/manual/en/latest/" },
  { name: "OpenGL", url: "https://www.khronos.org/opengl/wiki/Main_Page" },
  {
    name: "DirectX",
    url: "https://docs.microsoft.com/en-us/windows/win32/directx",
  },
  { name: "HTML", url: "https://developer.mozilla.org/en-US/docs/Web/HTML" },
  { name: "CSS", url: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
  {
    name: "JavaScript",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  { name: "TypeScript", url: "https://www.typescriptlang.org/docs/" },
  { name: "SASS", url: "https://sass-lang.com/documentation" },
  {
    name: "Bootstrap",
    url: "https://getbootstrap.com/docs/5.0/getting-started/introduction/",
  },
  { name: "Foundation", url: "https://get.foundation/sites/docs/" },
];
